import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import Sidebar from "./Components/Sidebar";
import Rightsection from "./Components/Rightsection";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Toaster position="bottom-center" richColors theme="dark" />

      <body className={inter.className}>
        <div className="h-full w-[100vw] bg-black flex justify-around relative items-center">
          <div className="w-[80vw] h-screen relative flex">
            <Sidebar />
            {children} 
            <Rightsection />
          </div>
        </div>
      </body>
    </html>
  );
}
